[package]
name = "app"
version = "0.1.0"
description = "A 3rd party manga reader for Mangadex and a manga tracker"
authors = ["Anton Fredriksson"]
license = "MIT License"
repository = "https://github.com/Phoeenix05/sakura"
default-run = "app"
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.4.0", features = ["macos-private-api", "http-request"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
