[package]
name = "tauri-app-ui"
version = "0.0.0"
edition = "2021"

[dependencies]
leptos = { version = "0.2", features = ["stable"] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
leptos_router = { version = "0.2.3", features = ["csr"] }
anyhow = "1.0.70"
reqwasm = "0.5.0"
serde_json = "1.0.94"
# tauri = "1.2.4"
# reqwest = "0.11.14"

[workspace]
members = ["src-tauri"]
