/// Generated by https://quicktype.io
// extern crate serde_json;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct MangaFeed {
    #[serde(rename = "result")]
    result: String,

    #[serde(rename = "response")]
    response: String,

    #[serde(rename = "data")]
    data: Vec<Datum>,

    #[serde(rename = "limit")]
    limit: i64,

    #[serde(rename = "offset")]
    offset: i64,

    #[serde(rename = "total")]
    total: i64,
}

#[derive(Serialize, Deserialize)]
pub struct Datum {
    #[serde(rename = "id")]
    id: String,

    #[serde(rename = "type")]
    datum_type: DatumType,

    #[serde(rename = "attributes")]
    attributes: Attributes,

    #[serde(rename = "relationships")]
    relationships: Vec<Relationship>,
}

#[derive(Serialize, Deserialize)]
pub struct Attributes {
    #[serde(rename = "volume")]
    volume: String,

    #[serde(rename = "chapter")]
    chapter: String,

    #[serde(rename = "title")]
    title: Title,

    #[serde(rename = "translatedLanguage")]
    translated_language: TranslatedLanguage,

    #[serde(rename = "externalUrl")]
    external_url: Option<String>,

    #[serde(rename = "publishAt")]
    publish_at: String,

    #[serde(rename = "readableAt")]
    readable_at: String,

    #[serde(rename = "createdAt")]
    created_at: String,

    #[serde(rename = "updatedAt")]
    updated_at: String,

    #[serde(rename = "pages")]
    pages: i64,

    #[serde(rename = "version")]
    version: i64,
}

#[derive(Serialize, Deserialize)]
pub struct Relationship {
    #[serde(rename = "id")]
    id: String,

    #[serde(rename = "type")]
    relationship_type: RelationshipType,
}

#[derive(Serialize, Deserialize)]
pub enum Title {
    #[serde(rename = "")]
    Empty,

    #[serde(rename = "Version 2")]
    Version2,
}

#[derive(Serialize, Deserialize)]
pub enum TranslatedLanguage {
    #[serde(rename = "en")]
    En,

    #[serde(rename = "fa")]
    Fa,

    #[serde(rename = "fr")]
    Fr,

    #[serde(rename = "id")]
    Id,

    #[serde(rename = "pl")]
    Pl,

    #[serde(rename = "pt-br")]
    PtBr,

    #[serde(rename = "ru")]
    Ru,
}

#[derive(Serialize, Deserialize)]
pub enum DatumType {
    #[serde(rename = "chapter")]
    Chapter,
}

#[derive(Serialize, Deserialize)]
pub enum RelationshipType {
    #[serde(rename = "manga")]
    Manga,

    #[serde(rename = "scanlation_group")]
    ScanlationGroup,

    #[serde(rename = "user")]
    User,
}
