<script setup lang="ts">
// Generated by https://quicktype.io

interface SearchResults {
    result: string;
    response: string;
    data: Datum[];
    limit: number;
    offset: number;
    total: number;
}

interface Datum {
    id: string;
    type: RelationshipType;
    attributes: DatumAttributes;
    relationships: Relationship[];
}

interface DatumAttributes {
    title: Title;
    altTitles: AltTitle[];
    description: PurpleDescription;
    isLocked: boolean;
    links: { [key: string]: string };
    originalLanguage: string;
    lastVolume: string;
    lastChapter: string;
    publicationDemographic: string;
    status: string;
    year: number | null;
    contentRating: string;
    tags: Tag[];
    state: string;
    chapterNumbersResetOnNewVolume: boolean;
    createdAt: string;
    updatedAt: string;
    version: number;
    availableTranslatedLanguages: string[];
    latestUploadedChapter: string;
}

interface AltTitle {
    ja?: string;
    en?: string;
    ru?: string;
    "ja-ro"?: string;
    ar?: string;
    tr?: string;
    uk?: string;
    fr?: string;
    pl?: string;
    it?: string;
    th?: string;
    "zh-hk"?: string;
    ko?: string;
    "es-la"?: string;
    fi?: string;
}

interface PurpleDescription {
    en: string;
    "es-la"?: string;
    ru?: string;
    "pt-br"?: string;
    it?: string;
}

interface Tag {
    id: string;
    type: TagType;
    attributes: TagAttributes;
    relationships: any[];
}

interface TagAttributes {
    name: Title;
    description: FluffyDescription;
    group: Group;
    version: number;
}

interface FluffyDescription {
}

enum Group {
    Format = "format",
    Genre = "genre",
    Theme = "theme",
}

interface Title {
    en: string;
}

enum TagType {
    Tag = "tag",
}

interface Relationship {
    id: string;
    type: RelationshipType;
    related?: string;
}

enum RelationshipType {
    Artist = "artist",
    Author = "author",
    CoverArt = "cover_art",
    Creator = "creator",
    Manga = "manga",
}

// ————————————————————————————————————————————————————————————
import { fetch } from "@tauri-apps/api/http";
import { useSearchHistory } from "../../stores/history";

const { query } = useRoute().params
const history = useSearchHistory()
history.addItem(query)

const { data, pending, error } = useAsyncData(async () => {
    const url = `https://api.mangadex.org/manga?title=${query}&limit=20&includes[]=cover_art&order[relevance]=desc`
    const res = await fetch<SearchResults>(url, {
        method: 'GET',
        timeout: 10,
        headers: {
            'User-Agent': localStorage.getItem('User-Agent')!
        }
    })
    return res.data
})
</script>

<template>
    <!-- Loading data -->
    <p v-if="pending">Loading...</p>

    <!-- Data loaded successfully -->
    <main v-if="!pending && !error">
        <NuxtLink v-for="manga in data?.data" :to="`/manga/${manga.id}`">
            <h3>{{ manga.attributes.title.en }}</h3>
        </NuxtLink>
    </main>

    <!-- Error occurred -->
    <code v-if="error">{{ error }}</code>
</template>