// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Relationship } from "./Relationship";
import type { RelationshipType } from "./RelationshipType";

export interface ApiObject<A, T = RelationshipType> { id: string, type: T, attributes: A, relationships: Array<Relationship>, }