// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { MangaDexDateTime } from "./MangaDexDateTime";

export interface AuthorAttributes { name: string, imageUrl: string | null, biography: Record, twitter: Url, pixiv: Url, melonBook: Url, fanBox: Url, booth: Url, nicoVideo: Url, skeb: Url, fantia: Url, tumblr: Url, youtube: Url, weibo: Url, naver: Url, website: Url, version: number, createdAt: MangaDexDateTime, updatedAt: MangaDexDateTime | null, }