// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { MangaDexDateTime } from "./MangaDexDateTime";

export interface AuthorAttributes { name: string, imageUrl: string | null, biography: Record, twitter: string, pixiv: string, melonBook: string, fanBox: string, booth: string, nicoVideo: string, skeb: string, fantia: string, tumblr: string, youtube: string, weibo: string, naver: string, website: string, version: number, createdAt: MangaDexDateTime, updatedAt: MangaDexDateTime | null, }