// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { MangaDexDateTime } from "./MangaDexDateTime";

export interface CoverAttributes { description: string, locale: Language | null, volume: string | null, fileName: string, createdAt: MangaDexDateTime, updatedAt: MangaDexDateTime | null, version: number, }