// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomListVisibility } from "./CustomListVisibility";

export interface CustomListAttributes { name: string, visibility: CustomListVisibility, version: number, }