// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MangaRelation = "adapted_from" | "alternate_story" | "alternate_version" | "based_on" | "colored" | "doujinshi" | "main_story" | "monochrome" | "prequel" | "preserialization" | "same_franchise" | "sequel" | "serialization" | "shared_universe" | "side_story" | "spin_off";