// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiObject } from "./ApiObject";
import type { ContentRating } from "./ContentRating";
import type { Demographic } from "./Demographic";
import type { Language } from "./Language";
import type { MangaDexDateTime } from "./MangaDexDateTime";
import type { MangaLinks } from "./MangaLinks";
import type { MangaState } from "./MangaState";
import type { MangaStatus } from "./MangaStatus";
import type { TagAttributes } from "./TagAttributes";

export interface MangaAttributes { title: Map<string, string>, altTitles: Array<Map<string, string>>, description: Map<string, string>, isLocked: boolean, links: MangaLinks | null, originalLanguage: Language, lastVolume: string | null, lastChapter: string | null, publicationDemographic: Demographic | null, status: MangaStatus, year: number | null, contentRating: ContentRating | null, chapterNumbersResetOnNewVolume: boolean, latestUploadedChapter: string, availableTranslatedLanguages: Array<Language>, tags: Array<ApiObject<TagAttributes>>, state: MangaState, createdAt: MangaDexDateTime, updatedAt: MangaDexDateTime | null, version: number, }