// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookWalker } from "./BookWalker";
import type { MangaUpdates } from "./MangaUpdates";
import type { MyAnimeList } from "./MyAnimeList";
import type { NovelUpdates } from "./NovelUpdates";

export interface MangaLinks { amz?: Url, al?: string, ap?: string, bw?: BookWalker, cdj?: string, ebj?: Url, engtl?: string, kt?: string, mu?: MangaUpdates, mal?: MyAnimeList, nu?: NovelUpdates, raw?: Url, }