// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorAttributes } from "./AuthorAttributes";
import type { ChapterAttributes } from "./ChapterAttributes";
import type { CoverAttributes } from "./CoverAttributes";
import type { CustomListAttributes } from "./CustomListAttributes";
import type { MangaAttributes } from "./MangaAttributes";
import type { ScanlationGroupAttributes } from "./ScanlationGroupAttributes";
import type { TagAttributes } from "./TagAttributes";
import type { UserAttributes } from "./UserAttributes";

export type RelatedAttributes = MangaAttributes | ChapterAttributes | CoverAttributes | AuthorAttributes | ScanlationGroupAttributes | TagAttributes | UserAttributes | CustomListAttributes;