// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { TagGroup } from "./TagGroup";

export interface TagAttributes { name: Record, description: Record, group: TagGroup, version: number, }