// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "./UserRole";

export interface UserAttributes { username: string, roles: Array<UserRole>, version: number, }