name: Build and Release

on:
  push:
    branches:
    - sakura

jobs:
  bundle:
    # strategy:
    #   matrix:
    #     os: [macos-latest, windows-latest]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install latest rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      
      - name: Install Tauri CLI
        run: cargo install tauri-cli --force
      
      - name: Build app bundle
        run: cargo tauri build
