name: Build and Release

on:
  push:
    tags:
      - 'v*[0-9].*[0-9].*[0-9]'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [20]
        pnpm-version: [8]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: | 
            ~/.cargo/registry
            ~/.cargo/git
            ./src-tauri/target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm tauri build
