name: Build and Release

on:
  push:
    branches:
    - sakura

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [20]
        pnpm-version: [8]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      
      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm tauri build
