name: Build and Release

on:
  push:
    branches:
    - sakura

jobs:
  build_releases:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install latest rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: tauri-cli
      
      - name: Build app bundle
        run: cargo tauri build
