<script setup lang="ts">
// Generated by https://quicktype.io

interface MangaFeed {
    result: string;
    response: string;
    data: Datum[];
    limit: number;
    offset: number;
    total: number;
}

interface Datum {
    id: string;
    type: DatumType;
    attributes: Attributes;
    relationships: Relationship[];
}

interface Attributes {
    volume: null | string;
    chapter: string;
    title: null | string;
    translatedLanguage: TranslatedLanguage;
    externalUrl: null;
    publishAt: string;
    readableAt: string;
    createdAt: string;
    updatedAt: string;
    pages: number;
    version: number;
}

enum TranslatedLanguage {
    Ar = "ar",
    En = "en",
    EsLa = "es-la",
    Fr = "fr",
    Hu = "hu",
    ID = "id",
    It = "it",
    Pl = "pl",
    PtBr = "pt-br",
    Ru = "ru",
    Tr = "tr",
    Uk = "uk",
    Vi = "vi",
}

interface Relationship {
    id: string;
    type: RelationshipType;
}

enum RelationshipType {
    Manga = "manga",
    ScanlationGroup = "scanlation_group",
    User = "user",
}

enum DatumType {
    Chapter = "chapter",
}

// ————————————————————————————————————————————————————————————
import { useFollowingStore } from "@/stores/following";
import { fetch } from "@tauri-apps/api/http";

const { id } = useRoute().params
const followed = useFollowingStore()

const { data, pending, error } = useAsyncData(async () => {
    const query = ["limit=500", "includes[]=cover_art", "includes[]=author", "translatedLanguage[]=en", "order[chapter]=desc"]
    const url = `https://api.mangadex.org/manga/${id}/feed?${query.join("&")}`
    const res = await fetch<MangaFeed>(url, {
        method: 'GET',
        timeout: 10,
        headers: {
            'User-Agent': localStorage.getItem('User-Agent')!
        }
    })
    return res.data
})
</script>

<template>
    <!-- Loading data -->
    <p v-if="pending">Loading...</p>

    <!-- Data loaded successfully -->
    <main v-if="!pending && !error">
        <br />

        <button @click="followed.addManga(id, '')">Follow</button>

        <br />
        <br />

        <NuxtLink v-for="chapter in data?.data" :to="`/chapter/${chapter.id}`">
            <h3>{{ chapter.attributes.title?.toString() }}</h3>
        </NuxtLink>
    </main>

    <!-- Error occurred -->
    <code v-if="error">{{ error }}</code>
</template>